# Generated by Django 5.2.3 on 2025-07-08 12:03

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('manager', account.models.UserManager()),
            ],
        ),
    ]
